// Auto-generated by CMake — do not edit.
// Include the generated version.h from the build tree, not this template.

#pragma once

/// @defgroup version Version Information
/// @{

/// @brief Full version string in "MAJOR.MINOR.PATCH" format.
#define LLMQUANT_VERSION        "1.4.0"

/// @brief Major version number.
#define LLMQUANT_VERSION_MAJOR  1

/// @brief Minor version number.
#define LLMQUANT_VERSION_MINOR  4

/// @brief Patch version number.
#define LLMQUANT_VERSION_PATCH  0

/// @brief Integer encoding: MAJOR*10000 + MINOR*100 + PATCH.
///
/// Useful for compile-time feature detection:
/// @code
/// #if LLMQUANT_VERSION_NUMBER >= 10100
///   // available since 1.1.0
/// #endif
/// @endcode
#define LLMQUANT_VERSION_NUMBER \
    (1 * 10000 + 4 * 100 + 0)

/// @brief Short git commit hash captured at configure time (e.g. "abc1234"),
///        or "unknown" if the build directory is not inside a git repository.
#define LLMQUANT_GIT_COMMIT "9693b75"

/// @brief ISO-8601 UTC timestamp of when CMake configure was last run
///        (e.g. "2026-03-21T14:30:00Z").  Baked in at configure time.
#define LLMQUANT_BUILD_TIMESTAMP "2026-03-23T10:34:00Z"

/// @}
