#pragma once
// LogitsProcessor.h — Logit distribution processing for LLM sampling.

#include <cstddef>
#include <cstdint>
#include <vector>

namespace llmquant {

/// Applies a chain of transformations to raw logit vectors to produce
/// a probability distribution suitable for token sampling.
class LogitsProcessor {
public:
    LogitsProcessor() = default;

    // ------------------------------------------------------------------
    // Transformations (modify logits in-place)
    // ------------------------------------------------------------------

    /// Divide each logit by *temperature*.  No-op when temperature == 1.0.
    /// Lower temperature → sharper distribution; higher → flatter.
    void apply_temperature(std::vector<float>& logits, float temperature) const;

    /// Reduce the logit of every token that has already been generated by
    /// dividing positive logits and multiplying negative logits by *penalty*.
    /// penalty > 1.0 discourages repetition; 1.0 = disabled.
    void apply_repetition_penalty(
        std::vector<float>&       logits,
        const std::vector<size_t>& generated_ids,
        float                      penalty) const;

    /// Zero out all but the top-*k* logits (set the rest to -infinity).
    void apply_top_k(std::vector<float>& logits, size_t k) const;

    /// Nucleus sampling: keep the smallest set of tokens whose cumulative
    /// softmax probability ≥ *p*, set the rest to -infinity.
    void apply_top_p(std::vector<float>& logits, float p) const;

    // ------------------------------------------------------------------
    // Probability conversion and sampling
    // ------------------------------------------------------------------

    /// Convert raw logits to a probability distribution via softmax.
    std::vector<float> softmax(const std::vector<float>& logits) const;

    /// Draw a token index by categorical sampling using *seed* as the RNG seed.
    size_t sample(const std::vector<float>& probs, uint64_t seed) const;

    /// Greedy decoding: return the index of the maximum logit.
    size_t greedy(const std::vector<float>& logits) const;

private:
    static constexpr float NEG_INF = -1e30f;
};

}  // namespace llmquant
